### ISSUE TITLE
Log is expired at README.md

### ISSUE THREAD

**Issue by DmytroLitvinov** [sobolevn/misspell-fixer-action#6]
In the README.md we have a next phrase: "See logs of our [own GitHub Actions](https://github.com/sobolevn/misspell-fixer-action/runs/520513568?check_suite_focus=true) with the fixed typo.", where link directs to GitHub action which shows that logs for this run have expired and are no longer available,

**Comment by sobolevn** [comment]
@DmytroLitvinov can you please delete it then? 🙂
