### ISSUE TITLE
Respect the '.misspell-fixer.ignore' file

### ISSUE THREAD

**Issue by lissy93** [sobolevn/misspell-fixer-action#8]
Hiya @sobolevn 
Awesome action - it is really useful, great work! :)

One problem that I am facing is that it doesn't seem to be using the `.misspell-fixer.ignore`, or maybe I have set it up incorrectly?

I basically just want to ignore my repos non-English translation files, so I created a [`.github/.misspell-fixer.ignore`](https://github.com/Lissy93/dashy/blob/master/.github/.misspell-fixer.ignore) file, but it still submits PRs for those files. Is this because the ignore file is not supported by your action?

**Comment by sobolevn** [comment]
Hi @Lissy93!

You can use this trick:
1. Check out your code with `@checkout-action`
2. Use https://github.com/sobolevn/misspell-fixer-action#options-and-outputs to specify arg and path to your `.misspell-fixer.ignore`

It should work for you! 👍 
Please, reopen if there are any problems.
